name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21.0.4+7.0.LTS'
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - uses: actions/upload-artifact@v4
        with:
          name: Launchpad Extension
          path: ./target/LaunchpadX.bwextension
